/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "sim_constants.h"

namespace hr { namespace franp { namespace rsim {

const simConstants g_sim_constants;

simConstants::simConstants() {
}

}}} // namespace

