/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef sim_CONSTANTS_H
#define sim_CONSTANTS_H

#include "sim_types.h"

namespace hr { namespace franp { namespace rsim {

class simConstants {
 public:
  simConstants();

};

extern const simConstants g_sim_constants;

}}} // namespace

#endif
