#!/bin/bash
#
# chkconfig: 35 90 12
# description: radar simulation server
#

# Get function from functions library
. /etc/init.d/functions

# Start the service FOO
start() {
        initlog -c "echo -n Starting radar simulator server: "
        /usr/bin/radar-sim-server &
        ### Create the lock file ###
        touch /var/lock/subsys/radar-sim-server
        success $"radar simulator server startup"
        echo
}

# Restart the service FOO
stop() {
        initlog -c "echo -n Stopping radar simulator server: "
        killproc radar-sim-server
        ### Now, delete the lock file ###
        rm -f /var/lock/subsys/radar-sim-server
        echo
}

### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status FOO
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac

exit 0